---
title: "recours_origine"
author: "Clémence Bracq"
date: "2024-03-28"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  markdown:
    wrap: 72
---




```{r, echo = FALSE}
indiv$s_medeciq_g_rec <- indiv$s_medeciq_g %>% 
  fct_recode(
    "Refus ou ne sait pas" = "-1",
    "Refus ou ne sait pas" = "-2"
  )  
indiv$s_traite_rec_rec <- indiv$s_traite_rec %>%
  fct_explicit_na("Refus ou ne sait pas")

indiv$s_etat2 <- indiv$s_etat %>%
  fct_recode(
    "Refus ou ne sait pas" = "Refus (ne pas lire)",
    "Refus ou ne sait pas" = "NSP (ne pas lire)"
  )
indiv$s_medeciq_a_rec <- indiv$s_medeciq_a %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv$s_medeciq_b_rec <- indiv$s_medeciq_b %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv$s_medeciq_c_rec <- indiv$s_medeciq_c %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv$s_medeciq_e_rec <- indiv$s_medeciq_e %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv$s_medeciq_f_rec <- indiv$s_medeciq_f %>%
  fct_explicit_na("Refus ou ne sait pas")


indiv <- indiv %>% 
  mutate(originegeo2 = case_when(group1=="Immigré (né étranger à l'étranger y compris réintégrés)"& originegeo_rec!="Espagne ou talie" ~originegeo_rec,
                                 group1=="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"~"France métropolitaine, non G2 Outre-mer ou immigré",
                                 originegeo_rec=="Espagne ou talie"~"Espagne ou Italie",
                                 group1!="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"& group1!="Immigré (né étranger à l'étranger y compris réintégrés)"~group1,
                                 TRUE~group1))

indiv$originegeo2 <- factor(indiv$originegeo2, levels = c("France métropolitaine, non G2 Outre-mer ou immigré", "Originaire de l'Outre-mer", "Descendant G2 d'un ou deux immigré-s", "Descendant G2 d'un ou deux originaire-s de l'Outre-mer", "Espagne ou Italie", "Portugal", "Autres pays de l'UE27", "Autres pays d'Europe", "Maroc ou Tunisie", "Algérie",  "Afrique guinéenne ou centrale", "Afrique sahélienne", "Autres pays d'Afrique", "Turquie ou Moyen-Orient", "Chine", "Asie du Sud-Est", "Autres pays d'Asie", "Autre pays"))


indiv <-  indiv %>% 
  mutate(s_traite_peau=case_when(s_compor_c_corrig=="Modalité citée"|s_compor_d_corrig=="Modalité citée"~"Couleur de peau",
                                  s_traite_rec_rec =="Oui"&s_compor_c_corrig!="Modalité citée"&s_compor_d_corrig!="Modalité citée"~"Autre motif",
                                  s_traite_rec_rec=="Non"~"Pas de discrimination",
                                  TRUE~"Refus ou ne sait pas"))
indiv_pd <-svydesign(ids = indiv$ident_fa, data = indiv, weights = indiv$poidsi)

indiv_femme <- indiv %>% filter(sexee=="Féminin")
indiv_femme$s_medeciq_d_rec <- indiv_femme$s_medeciq_d %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv_f_pd <-svydesign(ids = indiv_femme$ident_fa, data = indiv_femme, weights = indiv_femme$poidsi)

indiv_frott <- indiv_femme %>% filter(agenq>= 25) 
indiv_frott$frott_ap_25 <- indiv_frott$frott_ap_25 %>%
  fct_explicit_na("Refus ou ne sait pas")
indiv_frott_pd <-svydesign(ids = indiv_frott$ident_fa, data = indiv_frott, weights = indiv_frott$poidsi)
```

```{r, echo = FALSE}
ggsurvey(indiv_frott_pd) +
  aes(x = originegeo2, fill = frott_ap_25) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Dans les 3 dernières années..."
  ) +
  coord_flip() + scale_fill_manual(values=c("#40B330", "#FF4040", "#999999"))+
    theme(legend.position = "bottom")
```


```{r, echo = FALSE}
ggsurvey(indiv_f_pd) +
  aes(x = originegeo2, fill = s_medeciq_d_rec) +
  geom_bar(position = "fill") +
  # scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours au gynécologue"
  ) +
  coord_flip() + scale_fill_manual(values=c( "#FF4040","#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```

```{r, echo = FALSE}

ggsurvey(indiv_frott_pd) +
  aes(x = originegeo2, fill = s_medeciq_d_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours au gynécologue"
  ) +
  coord_flip() +scale_fill_manual(values=c( "#FF4040","#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```


```{r, echo = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_g_rec) +
  geom_bar(position = "fill") +
  # scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Pas de recours :"
  ) + scale_fill_manual(values=c("#999999", "#FF4040", "#40B330"))+
  coord_flip() +
  theme(legend.position = "bottom")
```

```{r}
tb <- lprop(svytable(~immig+s_medeciq_g_rec, indiv_pd))
tb <- as.data.frame(tb) 


tb %>%
 filter(!(immig %in% c("Ensemble"
))) %>% 
 filter(s_medeciq_g_rec %in% "Modalité citée") %>%
 ggplot() +
  aes(x = immig, weight = Freq) +
  geom_bar(fill = "#112446") +
  labs(
    x = NULL,
    y = "Proportion de non-recours"
  ) +
  theme(axis.text.x=element_text(angle=45, hjust=0.9))#+geom_hline(yintercept=5.2, linetype="dashed", color = "red")+annotate("text", x=13.5, y=6, label="Non-immigrés", color = "red", size=4.5)
```

```{r}
tb <- lprop(svytable(~originegeo2+s_medeciq_g_rec, indiv_pd))
tb <- as.data.frame(tb) 
tb2 <- sort(tb$Freq, decreasing=FALSE)


tb %>%
 filter(!(originegeo2 %in% c("France métropolitaine, non G2 Outre-mer ou immigré", "Originaire de l'Outre-mer", 
"Descendant G2 d'un ou deux immigré-s", "Descendant G2 d'un ou deux originaire-s de l'Outre-mer", "Ensemble"
))) %>% 
 filter(s_medeciq_g_rec %in% "Modalité citée") %>%
 ggplot() +
  aes(x = originegeo2, weight = Freq) +
  geom_bar(fill = "#112446") +
  labs(
    x = NULL,
    y = "Proportion de non-recours"
  ) +
  theme(axis.text.x=element_text(angle=45, hjust=0.9))+geom_hline(yintercept=5.2, linetype="dashed", color = "red")+annotate("text", x=13.5, y=6, label="Non-immigrés", color = "red", size=4.5)
```




```{r, echo = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_a_rec) +
  geom_bar(position = "fill") +
  # scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours au généraliste"
  ) + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  coord_flip() +
  theme(legend.position = "bottom") 
  # theme_minimal()
```


```{r, echo = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_b_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours au dentiste"
  ) +
  coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```


```{r, echo = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_c_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours à l'ophtalmologue"
  ) +
  coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```


```{r, echo = FALSE}

ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_e_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours au psychologue ou psychiatre"
  ) + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  coord_flip() +
  theme(legend.position = "bottom")
```


```{r, echo = FALSE}

ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_medeciq_f_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Recours à un autre spécialiste"
  ) +
  coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```


```{r}
ggsurvey(indiv_pd) +
    aes(x = originegeo2, fill = s_traite_rec_rec) +
    geom_bar(position = "fill") +
    scale_fill_hue(direction = 1) +
    labs(
        x = NULL,
        y = "Proportion",
        fill = "Discrimination par personnel médical"
    ) +
    coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
    theme(legend.position = "bottom") +
    theme_minimal()
```

```{r}
ggsurvey(indiv_pd) +
    aes(x = originegeo2, fill = s_traite_peau) +
    geom_bar(position = "fill") +
    scale_fill_hue(direction = 1) +
    labs(
        x = NULL,
        y = "Proportion",
        fill = "Discrimination par personnel médical"
    ) +
    coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
    theme(legend.position = "bottom") +
    theme_minimal()
```

```{r}
ggsurvey(indiv_pd) +
    aes(x = originegeo2, fill = s_traite_peau) +
    geom_bar(position = "fill") +
    scale_fill_hue(direction = 1) +
    labs(
        x = NULL,
        y = "Proportion",
        fill = "Discrimination par personnel médical"
    ) +
    coord_flip() + scale_fill_manual(values=c( "#D94602","#9C0824", "#40B330", "#999999"))+
    theme(legend.position = "bottom") 
```



```{r, echo = FALSE, fig.width=10}
ggsurvey(indiv_pd) +
  aes(x = originegeo_rec, fill = s_secuq) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Couverture sociale"
  ) +
  coord_flip() +
  theme(legend.position = "bottom") +
  theme_minimal()
```

```{r, echo  = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_renonc_rec) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Renoncement"
  ) +
  coord_flip() + scale_fill_manual(values=c( "#FF4040", "#40B330", "#999999"))+
  theme(legend.position = "bottom") 
```


```{r, echo = FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo2, fill = s_etat2) +
  geom_bar(position = "fill") +
  # scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Etat de santé perçu"
  ) +
  coord_flip() +scale_fill_manual(values=c( "#09622A","#519D54",  "#EAC34B", "#D94602", "#9C0824", "#999999"))+
  theme(legend.position = "bottom") 
  # theme_minimal()
```

```{r, echo =FALSE}
ggsurvey(indiv_pd) +
  aes(x = originegeo_rec, fill = agenq_cat) +
  geom_bar(position = "fill") +
  scale_fill_hue(direction = 1) +
  labs(
    x = NULL,
    y = "Proportion",
    fill = "Catégorie d'âge"
  ) +
  coord_flip() +
  theme(legend.position = "bottom") +
  theme_minimal()
```



