---
title: "Regressions recours"
author: "Clémence Bracq"
date: "2024-04-22"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  markdown:
    wrap: 72
---

# Modélisation {.tabset .tabset-fade}

```{r libraries, include=FALSE}
source("Libraries.R")
```

```{r base, include = FALSE}
teo_dist_ident <- read_parquet("distances_etab.parquet")
teo_dist_ident_lib <- read_parquet("distances_lib.parquet")

indiv_mod <- indiv_bdd %>% 
  left_join(teo_dist_ident, by = "ident_fa") %>% 
    left_join(teo_dist_ident_lib, by = "ident_fa")
# indiv_mod_pd <- svydesign(ids = indiv_mod$ident_fa, data = indiv_mod, weights = indiv_mod$poidsi)  
rm(teo_dist_ident, teo_dist_ident_lib)
gc()

```

```{r, include = FALSE}
enfants <- read_sas("X:/HAB-TEO2-exploitations/MàJ Insee avril 2023/enfants.sas7bdat",  catalog_file = "X:/HAB-TEO2-exploitations/MàJ Insee avril 2023/formats.sas7bcat")
indiv_test <- indiv_dist %>%  select(ident_fa, datenq, e_nbenf)
  enfants <- to_factor(enfants) %>% select(ident_fa, e_jnaise, e_mnaise, e_anaise) %>% left_join(indiv_test, by = "ident_fa")
  
  # Convertir les dates en objets Date
enfants$datenq <- as.Date(as.character(enfants$datenq), format = "%Y%m%d")
enfants$date_naise <- as.Date(paste(enfants$e_anaise, enfants$e_mnaise, enfants$e_jnaise, sep = "-"))

# Calculer la différence entre les deux dates en années
enfants$delai <- as.numeric(difftime(enfants$datenq, enfants$date_naise, units = "days")) / 365.25

# Créer l'indicateur pour savoir si les deux dates sont distantes de moins de 3 ans
enfants$nais_3ans <- ifelse(enfants$delai < 3, 1, 0)

enfants <- enfants %>% group_by(ident_fa) %>% mutate(nais_3ans_indiv = max(nais_3ans))
enfants_3ans <- enfants %>% select(ident_fa, nais_3ans_indiv) %>% distinct()
indiv_test<- indiv_test %>% 
  left_join(enfants_3ans, by = "ident_fa") 
indiv_test<- indiv_test %>% 
  mutate(nais_3ans =case_when(nais_3ans_indiv==1~"Naissance dans les trois dernières années",
                               nais_3ans_indiv==0~"Enfants mais pas de naissance\n dans les trois dernières années",
                                   e_nbenf==0~"Pas d'enfants", 
                                   TRUE ~ "Refus ou ne sait pas")) %>% 
  select(nais_3ans, ident_fa)
indiv_dist <- indiv_dist %>% 
  left_join(indiv_test, by = "ident_fa")

rm(enfants, enfants_3ans)
gc()


indiv_dist <- indiv_dist %>% 
  mutate(enfant = ifelse(nbenf>=1, "Un enfant ou plus", "Pas d'enfants"))
```


```{r, include = FALSE}
indiv_dist$frott_ap_25 <- as.factor(indiv_dist$frott_ap_25)
## Recodage de indiv$a_rorig en indiv$a_rorig_rec
indiv_dist$a_rorig_rec <- indiv_dist$a_rorig %>%
  fct_recode(
    "Refus ou ne sait pas" = "Refus (ne pas lire)",
    "Refus ou ne sait pas" = "NSP (ne pas lire)"
  ) %>%
  fct_explicit_na("Pas d'amis hors famille rencontrés \\ndans les deux dernières semaines")


## 17 mars 2020 deb premier confinement
indiv_dist <- indiv_dist %>% 
  mutate(covid = case_when(datenq>= 20200317~"Après covid", TRUE~"Avant covid"))
indiv_dist$covid <- relevel(as.factor(indiv_dist$covid), ref = "Avant covid")


indiv_dist$frott_ap_25 <- as.factor(indiv_dist$frott_ap_25)

indiv_dist <- indiv_dist %>% 
  mutate(prodesante = ifelse(p_naf88 %in% c(88, 87, 86), 1, 0))

indiv_dist$nais_3ans_rec <- indiv_dist$nais_3ans %>%
  fct_recode(
    "Enfants mais pas de naissance dans les trois dernières années" = "Enfants mais pas de naissance\n dans les trois dernières années",
    NULL = "Refus ou ne sait pas"
  )


indiv_dist <- indiv_dist %>% 
  mutate(contramed = case_when(c_nobbq_a=="Modalité citée"|c_nobbq_b=="Modalité citée"|c_nobbq_c=="Modalitée citée"~"Contraception médicale",
                               TRUE~"Pas de contraception médicale"))
indiv_dist$contramed <- relevel(as.factor(indiv_dist$contramed), ref="Contraception médicale")
indiv_dist$originegeo_rec2 <- indiv_dist$originegeo %>%
  fct_recode(
    "DOM" = "13"
  )

indiv_dist$s_etat_rec <- indiv_dist$s_etat %>%
  fct_recode(
    "Très bon ou bon" = "Très bon",
    "Très bon ou bon" = "Bon",
    "Moyen, mauvais ou très mauvais" = "Moyen",
    "Moyen, mauvais ou très mauvais" = "Mauvais",
    "Moyen, mauvais ou très mauvais" = "Très mauvais",
    NULL = "Refus (ne pas lire)",
    NULL = "NSP (ne pas lire)")

indiv_dist$q_franc <- indiv_dist$q_franc %>%
  fct_recode(NULL = "NSP (ne pas lire)")



indiv_dist$agenq_cat <- cut(indiv_dist$agenq, breaks = c(17, 24, 35, 45, 60))
indiv_dist$agenq_cat_rec <- indiv_dist$agenq_cat %>%
  fct_recode(
    "Moins de 25 ans" = "(17,24]",
    "Entre 25 et 35 ans" = "(24,35]",
    "Entre 35 et 45 ans" = "(35,45]",
    "Plus de 45 ans" = "(45,60]"
  )

indiv_dist$dist_min_urg_rec <- cut(indiv_dist$dist_min_urg, breaks = c(-1, 0, 1000, 3000, 5000, 10000, 37729))
## Recodage de indiv_dist$dist_min_urg_rec
indiv_dist$dist_min_urg_rec <- indiv_dist$dist_min_urg_rec %>%
  fct_recode(
    "Moins d'1 km" = "(-1,0]",
    "Moins d'1 km" = "(0,1e+03]",
    "Entre 1 et 3 km" = "(1e+03,3e+03]",
    "Entre 3 et 5 km" = "(3e+03,5e+03]",
    "Entre 5 et 10km" = "(5e+03,1e+04]",
    "Plus de 10km" = "(1e+04,3.77e+04]"
  )

indiv_dist$dist_min_mat_rec <- cut(indiv_dist$dist_min_mat, breaks = c(-1, 0, 1000, 3000, 5000, 10000, 52343.38))
## Recodage de indiv_dist$dist_min_urg en indiv_dist$dist_min_urg_rec
indiv_dist$dist_min_mat_rec <- indiv_dist$dist_min_mat_rec %>%
  fct_recode(
        "Moins d'1 km" = "(-1,0]",
    "Moins d'1 km" = "(0,1e+03]",
    "Entre 1 et 3 km" = "(1e+03,3e+03]",
    "Entre 3 et 5 km" = "(3e+03,5e+03]",
    "Entre 5 et 10km" = "(5e+03,1e+04]",
    "Plus de 10km" = "(1e+04,5.23e+04]"
  )

indiv_dist$lib_dist_min_gynéco_rec <- cut(indiv_dist$lib_dist_min_gynéco, breaks = c(-1, 0, 500, 1500, 4000, 8000, 57347.4))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_gynéco_rec <- indiv_dist$lib_dist_min_gynéco_rec %>%
  fct_recode(
        "Moins de 500m" = "(-1,0]",
    "Moins de 500m" = "(0,500]",
    "Entre 500m et 1.5km" = "(500,1.5e+03]",
    "Entre 1.5km et 4km" = "(1.5e+03,4e+03]",
    "Entre 4 et 8km" = "(4e+03,8e+03]",
    "Plus de 8km" = "(8e+03,5.73e+04]"
  )

indiv_dist$lib_dist_min_sf_rec <- cut(indiv_dist$lib_dist_min_sf, breaks = c(-1, 0, 500, 1500, 4000, 28433.5))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_sf_rec <- indiv_dist$lib_dist_min_sf_rec %>%
  fct_recode(
            "Moins de 500m" = "(-1,0]",
    "Moins de 500m" = "(0,500]",
    "Entre 500m et 1.5km" = "(500,1.5e+03]",
    "Entre 1.5km et 4km" = "(1.5e+03,4e+03]",
    "Plus de 4km" = "(4e+03,2.84e+04]"
  )
indiv_dist$lib_dist_min_medge_rec <- cut(indiv_dist$lib_dist_min_medge, breaks = c(-1, 0, 250, 500, 1000, 1500, 12353.5))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_medge_rec <- indiv_dist$lib_dist_min_medge_rec %>%
  fct_recode(
    "Moins de 250m" = "(-1,0]",
    "Moins de 250m" = "(0,250]",
    "Entre 250m et 500m" = "(250,500]",
    "Entre 500m et 1km" = "(500,1e+03]",
    "Entre 1 et 1.5km" = "(1e+03,1.5e+03]",
    "Plus d'1.5km" = "(1.5e+03,1.24e+04]"
  )

indiv_dist$com_apl_sagf_rec <- cut(indiv_dist$com_apl_sagf, breaks = c(-1, 0, 3, 6, 9, 19.210))
indiv_dist$com_apl_sagf_rec <- indiv_dist$com_apl_sagf_rec %>%
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,9]",
    "Fort" = "(9,19.2]",
  )
indiv_dist$com_apl_sagf_rec <- relevel(indiv_dist$com_apl_sagf_rec, ref = "Faible")

indiv_dist$iris_pct_immi_cat <- cut(indiv_dist$iris_pct_immi.y, breaks = c(-1,0, 3, 6, 10, 20, max(indiv_dist$iris_pct_immi.y)))
indiv_dist$iris_pct_immi_cat <- indiv_dist$iris_pct_immi_cat %>%
  fct_recode(
    "Entre 0 et 3% d'immigrés" = "(-1,0]",
    "Entre 0 et 3% d'immigrés" = "(0,3]",
    "Entre 3 et 10% d'immigrés" = "(3,6]",
    "Entre 6 et 10% d'immigrés" = "(6,10]",
    "Entre 10 et 20% d'immigrés" = "(10,20]",
    "20% d'immigrés et plus" = "(20,64.9]",
  )

indiv_dist$com_apl_mg_rec <- cut(indiv_dist$com_apl_mg, breaks = c(-1, 0, 50, 70, 90, 183.19))
indiv_dist$com_apl_mg_rec <- indiv_dist$com_apl_mg_rec %>%
  fct_recode(
    "Faible" = "(-1,0]",
    "Faible" = "(0,50]",
    "Plutôt faible" = "(50,70]",
    "Plutôt fort" = "(70,90]",
    "Fort" = "(90,183]",
  )
indiv_dist$com_apl_mg_rec <- relevel(indiv_dist$com_apl_mg_rec, ref = "Faible")
indiv_dist$com_apl_gyn_rec <- cut(indiv_dist$com_apl_gyn, breaks = c(-1, 0, 3, 6, 9, 21.400))
indiv_dist$com_apl_gyn_rec <- indiv_dist$com_apl_gyn_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,9]",
    "Fort" = "(9,21.4]",
  )
indiv_dist$com_apl_gyn_rec <- relevel(indiv_dist$com_apl_gyn_rec, ref = "Faible")

indiv_dist$com_apl_dent_rec <- cut(indiv_dist$com_apl_dent, breaks = c(-1, 0, 28, 47, 68, 281.31))
indiv_dist$com_apl_dent_rec <- indiv_dist$com_apl_dent_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,28]",
    "Plutôt faible" = "(28,47]",
    "Plutôt fort" = "(47,68]",
    "Fort" = "(68,281]",
  )
indiv_dist$com_apl_dent_rec <- relevel(indiv_dist$com_apl_dent_rec, ref = "Faible")


indiv_dist$com_apl_oph_rec <- cut(indiv_dist$com_apl_oph, breaks = c(-1, 0, 3, 6, 8, 17.18))
indiv_dist$com_apl_oph_rec <- indiv_dist$com_apl_oph_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,8]",
    "Fort" = "(8,17.2]",
  )
indiv_dist$com_apl_oph_rec <- relevel(indiv_dist$com_apl_oph_rec, ref = "Faible")


indiv_dist$com_apl_psy_rec <- cut(indiv_dist$com_apl_psy, breaks = c(-1, 0, 3, 6, 11, 43.07))
indiv_dist$com_apl_psy_rec <- indiv_dist$com_apl_psy_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,11]",
    "Fort" = "(11,43.1]",
  )
indiv_dist$com_apl_psy_rec <- relevel(indiv_dist$com_apl_psy_rec, ref = "Faible")


indiv_dist$agenq_cat_rec <- indiv_dist$agenq_cat %>%
  fct_recode(
    "Moins de 25 ans" = "(17,24]",
    "Entre 25 et 35 ans" = "(24,35]",
    "Entre 35 et 45 ans" = "(35,45]",
    "Plus de 45 ans" = "(45,60]"
  )

indiv_dist<- indiv_dist %>% 
  mutate(originegeo_rec2 = case_when(originegeo_rec=="France métropolitaine"~group1,
                                     TRUE~originegeo_rec))
indiv_dist$originegeo_rec2_rec <- indiv_dist$originegeo_rec2 %>%
  fct_recode(
    "France métropolitaine" = "Immigré (né étranger à l'étranger y compris réintégrés)",
    "DROM" = "Originaire de l'Outre-mer",
    "G2 Immigré" = "Descendant G2 d'un ou deux immigré-s",
    "G2 DROM" = "Descendant G2 d'un ou deux originaire-s de l'Outre-mer",
    "France métropolitaine" = "Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"
  )

indiv_dist <- indiv_dist %>% 
  mutate(originegeo2 = case_when(group1=="Immigré (né étranger à l'étranger y compris réintégrés)"& originegeo_rec!="Espagne ou talie" ~originegeo_rec,
                                 group1=="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"~"France métropolitaine, non G2 Outre-mer ou immigré",
                                 originegeo_rec=="Espagne ou talie"~"Espagne ou Italie",
                                 group1!="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"& group1!="Immigré (né étranger à l'étranger y compris réintégrés)"~group1,
                                 TRUE~group1))

indiv_dist$originegeo2 <- factor(indiv_dist$originegeo2, levels = c("France métropolitaine, non G2 Outre-mer ou immigré", "Originaire de l'Outre-mer", "Descendant G2 d'un ou deux immigré-s", "Descendant G2 d'un ou deux originaire-s de l'Outre-mer", "Espagne ou Italie", "Portugal", "Autres pays de l'UE27", "Autres pays d'Europe", "Maroc ou Tunisie", "Algérie",  "Afrique guinéenne ou centrale", "Afrique sahélienne", "Autres pays d'Afrique", "Turquie ou Moyen-Orient", "Chine", "Asie du Sud-Est", "Autres pays d'Asie", "Autre pays"))

indiv_dist <- indiv_dist %>% 
  mutate(iris_pct_imagh_afs = iris_pct_imagh + iris_pct_imafs) %>% 
  mutate(iris_pct_imeu = iris_pct_imeus + iris_pct_imue28)

indiv_reg <- indiv_dist %>% select(ident_fa, f_dip, uc_reve, frott_ap_25, s_medeciq_flag, couplee, agenq, agenq_cat_rec, prodesante, originegeo_rec, nais_3ans_rec, nais_3ans, contramed, enfant, originegeo2, s_etat_rec, csnq_ego, r_defcult, q_franc, a_rorig, s_traite, origine_tous_g2, dist_min_mat, dist_min_mat_rec, dist_min_urg,dist_min_urg_rec, lib_dist_min_medge, lib_dist_min_medge_rec, lib_dist_min_gynéco, lib_dist_min_gynéco_rec,a_rorig_rec,iris_pct_imchi, lib_dist_min_sf,lib_dist_min_sf_rec, com_apl_mg, com_apl_gyn, com_apl_sagf, urg_5km, mat_5km, lib_medge_1km, lib_sf_1km, lib_gynéco_1km, tuu2017, com_pop_ind_pond, l_immi, l_immi_rec, iris_pct_dip_bac, iris_pct_immi, iris_pct_imafs, iris_pct_imagh, iris_pct_imasie, iris_pct_imeus, iris_pct_imesp, iris_pct_imagh_afs, iris_pct_imeu,sexee, s_medeciq_a,nbenf, s_medeciq_b, s_medeciq_c, s_medeciq_d, s_medeciq_e, s_medeciq_f, s_medeciq_g, s_renonc,group1,originegeo_rec2,covid, com_apl_sagf_rec,com_apl_gyn_rec,com_apl_dent_rec, com_apl_oph_rec, com_apl_psy_rec, deract, c_nobbpq_e,contramed, iris_pct_immi_cat, com_apl_mg_rec, poidsi) 

indiv_reg <- indiv_reg %>%  filter(s_medeciq_flag=="A répondu")
indiv_reg <- indiv_reg %>% 
  mutate(originegeo2 = case_when(group1=="Immigré (né étranger à l'étranger y compris réintégrés)"& originegeo_rec!="Espagne ou talie" ~originegeo_rec,
                                 group1=="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"~"France métropolitaine, non G2 Outre-mer ou immigré",
                                 originegeo_rec=="Espagne ou talie"~"Espagne ou Italie",
                                 group1!="Population non immigrée ni originaire d'Outre-mer et descendant de deux parents non immigrés et non originaires d'Outre-mer"& group1!="Immigré (né étranger à l'étranger y compris réintégrés)"~group1,
                                 TRUE~group1))

indiv_reg$originegeo2 <- factor(indiv_reg$originegeo2, levels = c("France métropolitaine, non G2 Outre-mer ou immigré", "Originaire de l'Outre-mer", "Descendant G2 d'un ou deux immigré-s", "Descendant G2 d'un ou deux originaire-s de l'Outre-mer", "Espagne ou Italie", "Portugal", "Autres pays de l'UE27", "Autres pays d'Europe", "Maroc ou Tunisie", "Algérie",  "Afrique guinéenne ou centrale", "Afrique sahélienne", "Autres pays d'Afrique", "Turquie ou Moyen-Orient", "Chine", "Asie du Sud-Est", "Autres pays d'Asie", "Autre pays"))

# indiv_reg$r_defcult <- relevel(indiv_reg$r_defcult, ref = 'Rien de tout cela')
indiv_reg$s_traite <- relevel(indiv_reg$s_traite, ref = "Non")
indiv_reg$nais_3ans_rec <- relevel(indiv_reg$nais_3ans_rec, ref = "Pas d'enfants")
indiv_reg$l_immi_rec <- relevel(indiv_reg$l_immi_rec, ref = "Minorité immigrée")
indiv_reg$s_medeciq_a <- relevel(indiv_reg$s_medeciq_a, ref = "Modalité non citée")
indiv_reg$s_medeciq_b <- relevel(indiv_reg$s_medeciq_b, ref = "Modalité non citée")
indiv_reg$s_medeciq_c <- relevel(indiv_reg$s_medeciq_c, ref = "Modalité non citée")
indiv_reg$s_medeciq_e <- relevel(indiv_reg$s_medeciq_e, ref = "Modalité non citée")
indiv_reg$s_medeciq_f <- relevel(indiv_reg$s_medeciq_f, ref = "Modalité non citée")
indiv_reg$c_nobbpq_e <- relevel(indiv_reg$c_nobbpq_e, ref = "Modalité non citée")

indiv_reg$s_medeciq_g <- relevel(as.factor(indiv_reg$s_medeciq_g), ref = "Modalité non citée")
indiv_reg$s_renonc <- relevel(as.factor(indiv_reg$s_renonc), ref = "Non")
indiv_reg$couplee <- relevel(indiv_reg$couplee, ref = 'Ne vit pas en couple')
indiv_reg$csnq_ego <- relevel(indiv_reg$csnq_ego, ref = 'Cadre / profession libérale')
indiv_reg$agenq_cat_rec <- relevel(indiv_reg$agenq_cat_rec, ref = "Entre 35 et 45 ans")
indiv_reg$tuu2017 <- relevel(indiv_reg$tuu2017, ref = 'Unité urbaine de 200 000 à 1 999 999 habitants')
indiv_reg$originegeo_rec2 <- relevel(indiv_reg$originegeo_rec2, ref = "France métropolitaine")
indiv_reg$frott_ap_25 <- as.factor(indiv_reg$frott_ap_25) 
indiv_reg$frott_ap_25 <- relevel(indiv_reg$frott_ap_25, ref = 'Pas de frottis')
# indiv_reg$r_defcult <- relevel(indiv_reg$r_defcult, ref = 'Rien de tout cela')
indiv_reg$s_traite <- relevel(indiv_reg$s_traite, ref = "Non")
indiv_reg$nais_3ans_rec <- relevel(indiv_reg$nais_3ans_rec, ref = "Pas d'enfants")
indiv_reg$l_immi_rec <- relevel(indiv_reg$l_immi_rec, ref = "Minorité immigrée")

indiv_reg$couplee <- relevel(indiv_reg$couplee, ref = 'Ne vit pas en couple')
indiv_reg$csnq_ego <- relevel(indiv_reg$csnq_ego, ref = 'Cadre / profession libérale')
indiv_reg$agenq_cat_rec <- relevel(indiv_reg$agenq_cat_rec, ref = "Entre 35 et 45 ans")

indiv_reg$agenq_cat_rec2 <- indiv_reg$agenq_cat_rec %>%
  fct_recode(
    "Moins de 45 ans" = "Entre 35 et 45 ans",
    "Moins de 45 ans" = "Moins de 25 ans",
    "Plus de 45 ans" = "Entre 25 et 35 ans"
  )
indiv_reg$agenq_cat_rec2 <- relevel(indiv_reg$agenq_cat_rec2, ref = "Moins de 45 ans")
## Recodage de indiv_reg$couplee en indiv_reg$couplee_rec
indiv_reg$couplee_rec <- indiv_reg$couplee %>%
  fct_recode(
    "Couple cohabitant" = "Vit actuellement en couple avec une personne qui vit dans le logement",
    "Ne vit pas en couple" = "Vit actuellement en couple avec une personne qui vit en dehors du logement"
  )

indiv_reg <- indiv_reg %>% 
  mutate(csnq_actif = case_when(deract%in% c("Salariés", "Indépendant", "Variable", NA) ~ csnq_ego,
                                deract %in% c("Au chômage", "En formation, études") ~deract,
                                deract%in%c("Femme ou homme au foyer", "Autre inactifs") ~"Inactif"))

indiv_reg$csnq_actif_rec <- indiv_reg$csnq_actif %>%
  fct_recode(
    "Agriculteur, Artisan / Commerçant" = "Agriculteur",
    "Agriculteur, Artisan / Commerçant" = "Artisan / Commerçant",
    "Employé" = "Employé non qualifié",
    "Employé" = "Employé qualifié",
    "Inactif" = "En formation, études",
    "Inactif" = "Inactif",
    "Inactif" = "Jamais travaillé ou hors champ",
    "Ouvrier" = "Ouvrier non qualifié",
    "Ouvrier" = "Ouvrier qualifié"
  )

indiv_reg$csnq_actif_rec <- factor(indiv_reg$csnq_actif_rec, levels = c("Cadre / profession libérale", "Profession intermédiaire", "Agriculteur, Artisan / Commerçant Ouvrier", "Employé", "Ouvrier", "Au chômage", "Inactif", "NSP, refus, incodable"))

indiv_reg$csnq_actif_rec <- relevel(indiv_reg$csnq_actif_rec, ref = "Profession intermédiaire")


## Recodage de indiv_reg$csnq_ego en indiv_reg$csnq_ego_rec
indiv_reg$csnq_ego_rec <- indiv_reg$csnq_ego %>%
  fct_recode(
    "Classe supérieure" = "Cadre / profession libérale",
    "Classe moyenne" = "Agriculteur",
    "Classe moyenne" = "Artisan / Commerçant",
    "Classe moyenne" = "Profession intermédiaire",
    "Classe populaire" = "Employé qualifié",
    "Classe populaire" = "Employé non qualifié",
    "Classe populaire" = "Ouvrier qualifié",
    "Classe populaire" = "Ouvrier non qualifié",
    NULL = "NSP, refus, incodable"
  )

indiv_reg$s_traite_rec <- indiv_reg$s_traite %>%
  fct_recode(
    "Sans objet, refus ou ne sait pas" = "Refus (ne pas lire)",
    "Sans objet, refus ou ne sait pas" = "NSP (ne pas lire)",
    "Sans objet, refus ou ne sait pas" = "Sans objet")

indiv_reg$s_traite_rec2 <- indiv_reg$s_traite %>%
  fct_recode(
    "Refus ou ne sait pas" = "Refus (ne pas lire)",
    "Refus ou ne sait pas" = "NSP (ne pas lire)")
indiv_reg$tuu2017 <- indiv_reg$tuu2017 %>%
  fct_recode(
    "Moins de 2000 habitants" = "0")

indiv_reg <- indiv_reg %>% 
  mutate(diplome = case_when(f_dip%in% c("CAP, BEP ou diplôme de même niveau", "Baccalauréat technologique ou professionnel ou diplôme de même niveau", "Baccalauréat général, brevet supérieur, capacité en droit, DAEU ou diplôme étranger de même niveau")~ "Secondaire", 
                             f_dip%in% c("Diplôme de niveau BAC +1 ou +2", "Diplôme de niveau supérieur à BAC + 2")~"Supérieur",
                             TRUE~"Non diplômé du secondaire")) %>% 
           mutate(tr_revenu = dplyr::if_else(is.na(uc_reve),"Autres (manquants)",
                     if_else(uc_reve <= 763,"< D1",
                     if_else(uc_reve <= 1114,"D1 - Q1",
                     if_else(uc_reve <= 1600,"Q1 - Médiane",
                     if_else(uc_reve <= 2167, "Médiane - Q3",
                     if_else(uc_reve <= 3000, "Q3 - D9", 
                     "> D9")))))))
indiv_reg$tr_revenu <- factor(as.factor(indiv_reg$tr_revenu), levels = c("< D1", "D1 - Q1", "Q1 - Médiane", "Médiane - Q3", "Q3 - D9", "> D9", "Autres (manquants)"))
indiv_reg$tr_revenu <- relevel(indiv_reg$tr_revenu, ref = "Q1 - Médiane")
indiv_reg$diplome <- relevel(as.factor(indiv_reg$diplome), ref = "Secondaire")



indiv_reg$c_nobbpq_e_rec <- indiv_reg$c_nobbpq_e %>%
    fct_explicit_na("Modalité non citée")

    
indiv_reg_pd <-svydesign(ids = indiv_reg$ident_fa, data = indiv_reg, weights = indiv_reg$poidsi)
```


```{r, include = FALSE}
indiv_reg_frott <- indiv_reg %>% 
  filter(sexee=="Féminin") %>% filter(agenq >= 25)# 12 466

indiv_reg_frott_pd <-svydesign(ids = indiv_reg_frott$ident_fa, data = indiv_reg_frott, weights = indiv_reg_frott$poidsi)


indiv_reg_gyn <- indiv_reg %>% 
  filter(sexee=="Féminin")

indiv_reg_gyn_pd <-svydesign(ids = indiv_reg_gyn$ident_fa, data = indiv_reg_gyn, weights = indiv_reg_gyn$poidsi)

```

## Modèle de base

```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)


```



```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+contramed+covid +c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+ +contramed+covid+c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```

```{r, echo = FALSE, fig.height=8, fig.width=10}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("originegeo2" = "Origine", "couplee_rec" = "Couple", "agenq" = "Âge", "s_etat_rec" = "Etat de santé perçu", "q_franc" = "Maîtrise du français\n (évaluation par l'enquêteur.rice)",  "csnq_actif_rec" = "Classe sociale et activité", "nais_3ans_rec" = "Naissances dans les \n 3 dernières années", "agenq_cat_rec" = "Catégorie d'âge", "contramed"="Contraception", "c_nobbpq_e_rec" = "Jamais eu de rapports sexuels", "tr_revenu" ="Tranches de revenu", "diplome"="Diplôme"))#"s_traite_rec" = "Discrimination par \nprofessionnel de santé",
```

## Choix var socioéco
```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)


```



```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ 
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ csnq_actif_rec+diplome+tr_revenu
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~   
                   csnq_actif_rec+diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~csnq_actif_rec+diplome+tr_revenu
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```


```{r}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE)
```
Avec seulement diplôme et revenu

```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)


```



```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ 
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ diplome+tr_revenu
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~   
                   diplome+tr_revenu 
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~diplome+tr_revenu
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```


```{r}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE)
```



## Modèles avec segreg

### Seuls

#### iris_pct_immi en continu
```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
modela <- svyglm(as.factor(s_medeciq_a) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
modeld <- svyglm(as.factor(s_medeciq_d) ~ iris_pct_immi
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
model_frott <- svyglm(as.factor(frott_ap_25) ~iris_pct_immi
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
modelr <- svyglm(as.factor(s_renonc) ~ iris_pct_immi, family = quasibinomial,design = indiv_reg_pd)
```

```{r, echo = FALSE, fig.height=5, fig.width=8}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("iris_pct_immi"="Pourcentage d'immigrés dans l'IRIS"))
```


#### iris_pct_immi en quantile

```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
modela <- svyglm(as.factor(s_medeciq_a) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
modeld <- svyglm(as.factor(s_medeciq_d) ~ iris_pct_immi_cat
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
model_frott <- svyglm(as.factor(frott_ap_25) ~iris_pct_immi_cat
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
modelr <- svyglm(as.factor(s_renonc) ~ iris_pct_immi_cat, family = quasibinomial,design = indiv_reg_pd)
```

```{r, echo = FALSE, fig.height=5, fig.width=8}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("iris_pct_immi_cat"="Pourcentage d'immigrés dans l'IRIS"))
```
#### l_immi



```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modela <- svyglm(as.factor(s_medeciq_a) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modeld <- svyglm(as.factor(s_medeciq_d) ~ l_immi_rec
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
model_frott <- svyglm(as.factor(frott_ap_25) ~l_immi_rec
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
modelr <- svyglm(as.factor(s_renonc) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
```

```{r, echo = FALSE, fig.height=5, fig.width=8}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("l_immi_rec"="Part déclarée de personnes \nd'origine immigrée\n dans le quartier"))
```
### Avec origine

```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modela <- svyglm(as.factor(s_medeciq_a) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modeld <- svyglm(as.factor(s_medeciq_d) ~ iris_pct_immi_cat*originegeo2
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
model_frott <- svyglm(as.factor(frott_ap_25) ~iris_pct_immi_cat*originegeo2
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
modelr <- svyglm(as.factor(s_renonc) ~ iris_pct_immi_cat*originegeo2, family = quasibinomial,design = indiv_reg_pd)
```

```{r, echo = FALSE, fig.height=5, fig.width=8}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("iris_pct_immi_cat"="Pourcentage d'immigrés dans l'IRIS"))
```

### Avec modèle de base

```{r}
modelg <- svyglm(as.factor(s_medeciq_g) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)


```



```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat+q_franc+contramed+covid +c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~   originegeo2 +
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+iris_pct_immi_cat+q_franc+ +contramed+covid+c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```

```{r, echo = FALSE, fig.height=8, fig.width=10}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele, "Autre spé." =modelf, "Gynéco."=modeld, "Frottis"=model_frott, "Non-rec." = modelg, "Renonc." = modelr), type = "faceted", exponentiate = TRUE, include = "iris_pct_immi_cat")#"s_traite_rec" = "Discrimination par \nprofessionnel de santé",
```







####Avec tuu 2017


```{r, include =FALSE}
modelg <- svyglm(as.factor(s_medeciq_g) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_ego +
                   covid+iris_pct_immi_cat+
                   couplee_rec  +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017# +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)


modela <- svyglm(as.factor(s_medeciq_a) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_ego +
                   covid+iris_pct_immi_cat+
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+iris_pct_immi_cat+
                  # origine_tous_g2+
                   csnq_ego +
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_ego +
                   covid+iris_pct_immi_cat+
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+iris_pct_immi_cat+
                  # origine_tous_g2+
                   csnq_ego +
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_ego +
                   covid+iris_pct_immi_cat+
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelr <- svyglm(as.factor(s_renonc) ~   originegeo_rec2 +
                  agenq+nbenf+
                  s_etat_rec+
                  q_franc+
                  s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_ego +
                   covid+iris_pct_immi_cat+
                   couplee_rec +
                  # nbenf +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  tuu2017 #+
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
```

```{r, echo = FALSE, fig.height=8, fig.width=10}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo"=modelc,  "Psy"= modele, "Autre spé" =modelf, "0" = modelg, "Renoncement" = modelr), type = "faceted", exponentiate = TRUE, variable_labels = c("originegeo_rec2" = "Origine", "couplee_rec" = "Couple", "agenq" = "Âge", "s_etat_rec" = "Etat de santé perçu", "q_franc" = "Maîtrise du français\n (évaluation par l'enquêteur.rice)", "s_traite_rec" = "Discrimination par \nprofessionnel de santé", "csnq_ego" = "Classe sociale", "tuu2017" = "Type d'unité géographique"))
```

Interaction?


## Modèles avec accès

### Seuls

```{r}
#modelg <- svyglm(as.factor(s_medeciq_g) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modela <- svyglm(as.factor(s_medeciq_a) ~ lib_dist_min_medge_rec +dist_min_urg_rec, family = quasibinomial,design = indiv_reg_pd)
modela2 <- svyglm(as.factor(s_medeciq_a) ~ lib_dist_min_medge+dist_min_urg, family = quasibinomial,design = indiv_reg_pd)
modela3 <- svyglm(as.factor(s_medeciq_a) ~ com_apl_mg_rec, family = quasibinomial,design = indiv_reg_pd)
modela4 <- svyglm(as.factor(s_medeciq_a) ~ com_apl_mg, family = quasibinomial,design = indiv_reg_pd)
modela5 <- svyglm(as.factor(s_medeciq_a) ~ lib_medge_1km +urg_5km, family = quasibinomial,design = indiv_reg_pd)
```

```{r}
ggstats::ggcoef_compare(list(modela , modela2, modela5,  modela3, modela4), type = "faceted", exponentiate = TRUE, variable_labels = c("lib_dist_min_medge_rec"="Distance au médecin généraliste (discret)", "dist_min_urg_rec" = "Distance aux urgences (discret)","lib_dist_min_medge"="Distance au médecin généraliste (continu)", "dist_min_urg" = "Distance aux urgences (continu)","lib_medge_1km" = "Nombre de médecin généraliste\n dans un rayon d'1 km",  "urg_5km" = "Nombre d'urgences\n dans un rayon de 5 km", "com_apl_mg_rec" = "APL au médecin généraliste (discret)", "com_apl_mg" = "APL au médecin généraliste (continu)"))#"Distances \n (discret)" = modela , "Distances \n (continu)"=modela2, "Nombre" = modela5, "APL \n (discret)" = modela3, "APL \n (continu)" =modela4
```

```{r}
modelb <- svyglm(as.factor(s_medeciq_b) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)

modele <- svyglm(as.factor(s_medeciq_e) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
modelf <- svyglm(as.factor(s_medeciq_f) ~ l_immi_rec, family = quasibinomial,design = indiv_reg_pd)
```


```{r}
modelfr <- svyglm(as.factor(frott_ap_25) ~ lib_dist_min_gynéco_rec+lib_dist_min_sf_rec+ dist_min_mat_rec, family = quasibinomial,design = indiv_reg_frott_pd)
modelfr2 <- svyglm(as.factor(frott_ap_25) ~ lib_dist_min_gynéco+lib_dist_min_sf+ dist_min_mat , family = quasibinomial,design = indiv_reg_frott_pd)
modelfr3 <- svyglm(as.factor(frott_ap_25) ~ com_apl_sagf_rec+com_apl_gyn_rec, family = quasibinomial,design = indiv_reg_frott_pd)
modelfr4 <- svyglm(as.factor(frott_ap_25) ~ com_apl_gyn +com_apl_sagf, family = quasibinomial,design = indiv_reg_frott_pd)
modelfr5 <- svyglm(as.factor(frott_ap_25) ~ lib_gynéco_1km+lib_sf_1km+mat_5km, family = quasibinomial,design = indiv_reg_frott_pd)
```



```{r}
ggstats::ggcoef_compare(list(modelfr , modelfr2,  modelfr5,modelfr3, modelfr4), type = "faceted", exponentiate = TRUE, variable_labels = c("lib_dist_min_gynéco_rec"="Distance au gynécologue (discret)","lib_dist_min_sf_rec"="Distance à la sage-femme (discret)", "dist_min_mat_rec" = "Distance à la maternité (discret)","lib_dist_min_gynéco"="Distance au gynécologue (continu)","lib_dist_min_sf"="Distance à la sage-femme (continu)", "dist_min_mat" = "Distance à la maternité (continu)","lib_gynéco_1km" = "Nombre de gynécologues\n dans un rayon d'1 km","lib_sf_1km" = "Nombre de sages-femmes\n dans un rayon d'1 km",  "mat_5km" = "Nombre de maternités\n dans un rayon de 5 km", "com_apl_sagf_rec" = "APL aux sages-femmes (discret)","com_apl_gyn_rec" = "APL aux gynécologues (discret)", "com_apl_sagf" = "APL aux sages-femmes (continu)", "com_apl_gyn" = "APL aux gynécologues (continu)"))#"s_traite_rec" = "Discrimination par \nprofessionnel de santé",
```


```{r}


modeld <- svyglm(as.factor(s_medeciq_d) ~ lib_dist_min_gynéco_rec + dist_min_mat_rec +dist_min_urg_rec, family = quasibinomial,design = indiv_reg_gyn_pd)
modeld2 <- svyglm(as.factor(s_medeciq_d) ~ lib_dist_min_gynéco+ dist_min_mat +dist_min_urg, family = quasibinomial,design = indiv_reg_gyn_pd)
modeld3 <- svyglm(as.factor(s_medeciq_d) ~ com_apl_gyn_rec, family = quasibinomial,design = indiv_reg_gyn_pd)
modeld4 <- svyglm(as.factor(s_medeciq_d) ~ com_apl_gyn, family = quasibinomial,design = indiv_reg_gyn_pd)
modeld5 <- svyglm(as.factor(s_medeciq_d) ~ lib_gynéco_1km +mat_5km+urg_5km, family = quasibinomial,design = indiv_reg_gyn_pd)
```

```{r}
ggstats::ggcoef_compare(list(modeld , modeld2, modeld3, modeld4, modeld5), type = "faceted", exponentiate = TRUE)#"s_traite_rec" = "Discrimination par \nprofessionnel de santé",
```



```{r}
modela3 <- svyglm(as.factor(s_medeciq_a) ~ com_apl_mg_rec, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ com_apl_dent_rec, family = quasibinomial,design = indiv_reg_pd)
modelc <-svyglm(as.factor(s_medeciq_c) ~ com_apl_oph_rec, family = quasibinomial,design = indiv_reg_pd)
modeld3 <- svyglm(as.factor(s_medeciq_d) ~ com_apl_gyn_rec, family = quasibinomial,design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ com_apl_psy_rec, family = quasibinomial,design = indiv_reg_pd)
modelfr3 <- svyglm(as.factor(frott_ap_25) ~ com_apl_sagf_rec+com_apl_gyn_rec, family = quasibinomial,design = indiv_reg_frott_pd)
```

```{r}
ggstats::ggcoef_compare(list("Généraliste"=modela3  ,"Gynéco."= modeld3,  "Frottis"=modelfr3, "Psy."= modele, "Dentiste"=modelb,  "Ophtalmo."=modelc), type = "faceted", exponentiate = TRUE, variable_labels = c("com_apl_mg_rec"="APL généraliste", "com_apl_dent_rec" = "APL dentiste", "com_apl_oph_rec"="APL ophtalmologue", "com_apl_gyn_rec"="APL gynécologue", "com_apl_psy_rec"="APL psychologue", "com_apl_sagf_rec"="APL sage-femme"))
```

### Avec tuu2017

```{r}
modela3 <- svyglm(as.factor(s_medeciq_a) ~ com_apl_mg_rec +tuu2017, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ com_apl_dent_rec+tuu2017, family = quasibinomial,design = indiv_reg_pd)
modelc <-svyglm(as.factor(s_medeciq_c) ~ com_apl_oph_rec + tuu2017, family = quasibinomial,design = indiv_reg_pd)
modeld3 <- svyglm(as.factor(s_medeciq_d) ~ com_apl_gyn_rec+tuu2017, family = quasibinomial,design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ com_apl_psy_rec+tuu2017, family = quasibinomial,design = indiv_reg_pd)
modelfr3 <- svyglm(as.factor(frott_ap_25) ~ com_apl_sagf_rec+com_apl_gyn_rec+tuu2017, family = quasibinomial,design = indiv_reg_frott_pd)
```

```{r}
ggstats::ggcoef_compare(list("Généraliste"=modela3  ,"Gynéco."= modeld3,  "Frottis"=modelfr3, "Psy."= modele, "Dentiste"=modelb,  "Ophtalmo."=modelc), type = "faceted", exponentiate = TRUE)
```

### Avec interaction origine

```{r}
modela3 <- svyglm(as.factor(s_medeciq_a) ~ com_apl_mg_rec*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~ com_apl_dent_rec*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelc <-svyglm(as.factor(s_medeciq_c) ~ com_apl_oph_rec*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modeld3 <- svyglm(as.factor(s_medeciq_d) ~ com_apl_gyn_rec*originegeo2, family = quasibinomial,design = indiv_reg_gyn_pd)
modele <- svyglm(as.factor(s_medeciq_e) ~ com_apl_psy_rec*originegeo2, family = quasibinomial,design = indiv_reg_pd)
modelfr3 <- svyglm(as.factor(frott_ap_25) ~ com_apl_sagf_rec*originegeo2+com_apl_gyn_rec*originegeo2, family = quasibinomial,design = indiv_reg_frott_pd)
```

```{r}
ggstats::ggcoef_model(modela3, exponentiate = TRUE)#donne rien
ggstats::ggcoef_model(modeld3, exponentiate = TRUE, variable_labels = c("com_apl_gyn_rec"="APL Gynécologue", "originegeo2" = "Origine", "com_apl_gyn_rec:originegeo2"="APL et origine"))# Pas d'effet de la proximité pour chinois?
ggstats::ggcoef_model(modelfr3, exponentiate = TRUE)# donne rien, pas assez de gens
# ggstats::ggcoef_model(modele, exponentiate = TRUE)# donne rien, pas assez de gens
ggstats::ggcoef_model(modelb, exponentiate = TRUE)#donne rien
ggstats::ggcoef_model(modelc, exponentiate = TRUE, variable_labels = c("com_apl_oph_rec"="APL Ophtalmologue", "originegeo2" = "Origine", "com_apl_oph_rec:originegeo2"="APL et origine"))# Pas d'effet de la proximité pour chinois?
#,"Gynéco."= modeld3,  "Frottis"=modelfr3, "Psy."= modele, "Dentiste"=modelb,  "Ophtalmo."=modelc),
```

### Avec le reste 

```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   originegeo2 +com_apl_mg_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~   originegeo2 +com_apl_dent_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   originegeo2 +com_apl_oph_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+contramed+covid +c_nobbpq_e_rec+com_apl_gyn_rec
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   originegeo2 +com_apl_psy_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~com_apl_gyn_rec+com_apl_sagf_rec+ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+originegeo2+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+ +contramed+covid+c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```

```{r, echo = FALSE, fig.height=8, fig.width=10}
ggstats::ggcoef_compare(list("Généraliste"=modela , "Dentiste" =modelb, "Ophtalmo."=modelc,  "Psy."= modele,  "Gynéco."=modeld, "Frottis"=model_frott), type = "faceted", exponentiate = TRUE, variable_labels = c("originegeo2" = "Origine", "couplee_rec" = "Couple", "agenq" = "Âge", "s_etat_rec" = "Etat de santé perçu", "q_franc" = "Maîtrise du français\n (évaluation par l'enquêteur.rice)",  "csnq_actif_rec" = "Classe sociale et activité", "nais_3ans_rec" = "Naissances dans les \n 3 dernières années", "agenq_cat_rec" = "Catégorie d'âge", "contramed"="Contraception", "c_nobbpq_e_rec" = "Jamais eu de rapports sexuels", "tr_revenu" ="Tranches de revenu", "diplome"="Diplôme"))#"s_traite_rec" = "Discrimination par \nprofessionnel de santé",
```

### Avec le reste et interaction

```{r, include = FALSE}
modela <- svyglm(as.factor(s_medeciq_a) ~   originegeo2*com_apl_mg_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelb <- svyglm(as.factor(s_medeciq_b) ~   originegeo2*com_apl_dent_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)
modelc <- svyglm(as.factor(s_medeciq_c) ~   originegeo2*com_apl_oph_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   covid+
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

modeld <- svyglm(as.factor(s_medeciq_d) ~ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+contramed+covid +c_nobbpq_e_rec+com_apl_gyn_rec*originegeo2
             , family = quasibinomial,
  design = indiv_reg_gyn_pd)


modele <- svyglm(as.factor(s_medeciq_e) ~   originegeo2*com_apl_psy_rec+
                  agenq+enfant+
                  s_etat_rec+
                  q_franc+
                  # s_traite_rec+
                  sexee +
                   covid+
                  # origine_tous_g2+
                   csnq_actif_rec+diplome+tr_revenu +
                   couplee_rec #+
                  # enfant +
                  # durtotfrm +
                  # a_rfami+
                  # a_ramis+
                  # a_retud+
                  # a_rorig+
                  # a_rquart+
                  # tuu2017 +
                  # l_immi +
                  # iris_pct_sedent +
                  # iris_pct_immi
                ,family = quasibinomial,
                design = indiv_reg_pd)

model_frott <- svyglm(as.factor(frott_ap_25) ~com_apl_gyn_rec*originegeo2+com_apl_sagf_rec*originegeo2+ nais_3ans_rec+couplee_rec+agenq_cat_rec+agenq+s_etat_rec+csnq_actif_rec+diplome+tr_revenu+q_franc+ +contramed+covid+c_nobbpq_e_rec
             , family = quasibinomial,
  design = indiv_reg_frott_pd)
```

```{r}
ggstats::ggcoef_model(modela, exponentiate = TRUE, include = c("originegeo2", "com_apl_mg_rec","originegeo2:com_apl_mg_rec"))#Chine 
ggstats::ggcoef_model(modeld, exponentiate = TRUE, include = c("originegeo2", "com_apl_gyn_rec","com_apl_gyn_rec:originegeo2"))# donne rien
 ggstats::ggcoef_model(model_frott, exponentiate = TRUE,  include = c("originegeo2", "com_apl_gyn_rec","com_apl_gyn_rec:originegeo2", "com_apl_sagf_rec", "originegeo2:com_apl_sagf_rec"))# donne rien, pas assez de gens
 ggstats::ggcoef_model(modele, exponentiate = TRUE, include = c("originegeo2", "com_apl_psy_rec","originegeo2:com_apl_psy_rec"))# donne rien, pas assez de gens
ggstats::ggcoef_model(modelb, exponentiate = TRUE, include = c("originegeo2", "com_apl_dent_rec","originegeo2:com_apl_dent_rec"))#donne rien
ggstats::ggcoef_model(modelc, exponentiate = TRUE, include = c("originegeo2", "com_apl_oph_rec","originegeo2:com_apl_oph_rec"))# Pas d'effet de la proximité pour chinois?

```

