---
title: "Reg_distances_final"
author: "Clémence Bracq"
date: "2024-05-14"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  markdown:
    wrap: 72
---

```{r}
indiv_dist$poidsi_entier <- round(indiv_dist$poidsi)
indiv_dist$dist_min_urg_rec <- cut(indiv_dist$dist_min_urg, breaks = c(-1, 0, 1000, 3000, 5000, 10000, 37729))
## Recodage de indiv_dist$dist_min_urg_rec
indiv_dist$dist_min_urg_rec <- indiv_dist$dist_min_urg_rec %>%
  fct_recode(
    "Moins d'1 km" = "(-1,0]",
    "Moins d'1 km" = "(0,1e+03]",
    "Entre 1 et 3 km" = "(1e+03,3e+03]",
    "Entre 3 et 5 km" = "(3e+03,5e+03]",
    "Entre 5 et 10km" = "(5e+03,1e+04]",
    "Plus de 10km" = "(1e+04,3.77e+04]"
  )

indiv_dist$dist_min_mat_rec <- cut(indiv_dist$dist_min_mat, breaks = c(-1, 0, 1000, 3000, 5000, 10000, 52343.38))
## Recodage de indiv_dist$dist_min_urg en indiv_dist$dist_min_urg_rec
indiv_dist$dist_min_mat_rec <- indiv_dist$dist_min_mat_rec %>%
  fct_recode(
        "Moins d'1 km" = "(-1,0]",
    "Moins d'1 km" = "(0,1e+03]",
    "Entre 1 et 3 km" = "(1e+03,3e+03]",
    "Entre 3 et 5 km" = "(3e+03,5e+03]",
    "Entre 5 et 10km" = "(5e+03,1e+04]",
    "Plus de 10km" = "(1e+04,5.23e+04]"
  )

indiv_dist$lib_dist_min_gynéco_rec <- cut(indiv_dist$lib_dist_min_gynéco, breaks = c(-1, 0, 500, 1500, 4000, 8000, 57347.4))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_gynéco_rec <- indiv_dist$lib_dist_min_gynéco_rec %>%
  fct_recode(
        "Moins de 500m" = "(-1,0]",
    "Moins de 500m" = "(0,500]",
    "Entre 500m et 1.5km" = "(500,1.5e+03]",
    "Entre 1.5km et 4km" = "(1.5e+03,4e+03]",
    "Entre 4 et 8km" = "(4e+03,8e+03]",
    "Plus de 8km" = "(8e+03,5.73e+04]"
  )

indiv_dist$lib_dist_min_sf_rec <- cut(indiv_dist$lib_dist_min_sf, breaks = c(-1, 0, 500, 1500, 4000, 28433.5))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_sf_rec <- indiv_dist$lib_dist_min_sf_rec %>%
  fct_recode(
            "Moins de 500m" = "(-1,0]",
    "Moins de 500m" = "(0,500]",
    "Entre 500m et 1.5km" = "(500,1.5e+03]",
    "Entre 1.5km et 4km" = "(1.5e+03,4e+03]",
    "Plus de 4km" = "(4e+03,2.84e+04]"
  )
indiv_dist$lib_dist_min_medge_rec <- cut(indiv_dist$lib_dist_min_medge, breaks = c(-1, 0, 250, 500, 1000, 1500, 12353.5))
## Recodage de indiv_dist$lib_dist_min_gynéco_rec en indiv_dist$lib_dist_min_gynéco_rec_rec
indiv_dist$lib_dist_min_medge_rec <- indiv_dist$lib_dist_min_medge_rec %>%
  fct_recode(
    "Moins de 250m" = "(-1,0]",
    "Moins de 250m" = "(0,250]",
    "Entre 250m et 500m" = "(250,500]",
    "Entre 500m et 1km" = "(500,1e+03]",
    "Entre 1 et 1.5km" = "(1e+03,1.5e+03]",
    "Plus d'1.5km" = "(1.5e+03,1.24e+04]"
  )

indiv_dist$com_apl_sagf_rec <- cut(indiv_dist$com_apl_sagf, breaks = c(-1, 0, 3, 6, 9, 19.210))
indiv_dist$com_apl_sagf_rec <- indiv_dist$com_apl_sagf_rec %>%
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,9]",
    "Fort" = "(9,19.2]",
  )
indiv_dist$com_apl_sagf_rec <- relevel(indiv_dist$com_apl_mg_rec, ref = "Faible")

indiv_dist$iris_pct_immi_cat <- cut(indiv_dist$iris_pct_immi.y, breaks = c(-1,0, 3, 6, 10, 20, max(indiv_dist$iris_pct_immi.y)))
indiv_dist$iris_pct_immi_cat <- indiv_dist$iris_pct_immi_cat %>%
  fct_recode(
    "Entre 0 et 3% d'immigrés" = "(-1,0]",
    "Entre 0 et 3% d'immigrés" = "(0,3]",
    "Entre 3 et 10% d'immigrés" = "(3,6]",
    "Entre 6 et 10% d'immigrés" = "(6,10]",
    "Entre 10 et 20% d'immigrés" = "(10,20]",
    "20% d'immigrés et plus" = "(20,64.9]",
  )

indiv_dist$com_apl_mg_rec <- cut(indiv_dist$com_apl_mg, breaks = c(-1, 0, 50, 70, 90, 183.19))
indiv_dist$com_apl_mg_rec <- indiv_dist$com_apl_mg_rec %>%
  fct_recode(
    "Faible" = "(-1,0]",
    "Faible" = "(0,50]",
    "Plutôt faible" = "(50,70]",
    "Plutôt fort" = "(70,90]",
    "Fort" = "(90,183]",
  )
indiv_dist$com_apl_mg_rec <- relevel(indiv_dist$com_apl_mg_rec, ref = "Faible")
indiv_dist$com_apl_gyn_rec <- cut(indiv_dist$com_apl_gyn, breaks = c(-1, 0, 3, 6, 9, 21.400))
indiv_dist$com_apl_gyn_rec <- indiv_dist$com_apl_gyn_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,9]",
    "Fort" = "(9,21.4]",
  )
indiv_dist$com_apl_gyn_rec <- relevel(indiv_dist$com_apl_gyn_rec, ref = "Faible")

indiv_dist$com_apl_dent_rec <- cut(indiv_dist$com_apl_dent, breaks = c(-1, 0, 28, 47, 68, 281.31))
indiv_dist$com_apl_dent_rec <- indiv_dist$com_apl_dent_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,28]",
    "Plutôt faible" = "(28,47]",
    "Plutôt fort" = "(47,68]",
    "Fort" = "(68,281]",
  )
indiv_dist$com_apl_dent_rec <- relevel(indiv_dist$com_apl_dent_rec, ref = "Faible")


indiv_dist$com_apl_oph_rec <- cut(indiv_dist$com_apl_oph, breaks = c(-1, 0, 3, 6, 8, 17.18))
indiv_dist$com_apl_oph_rec <- indiv_dist$com_apl_oph_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,8]",
    "Fort" = "(8,17.2]",
  )
indiv_dist$com_apl_oph_rec <- relevel(indiv_dist$com_apl_oph_rec, ref = "Faible")


indiv_dist$com_apl_psy_rec <- cut(indiv_dist$com_apl_psy, breaks = c(-1, 0, 3, 6, 11, 43.07))
indiv_dist$com_apl_psy_rec <- indiv_dist$com_apl_psy_rec %>%# distrib quantiles
  fct_recode(
        "Faible" = "(-1,0]",
    "Faible" = "(0,3]",
    "Plutôt faible" = "(3,6]",
    "Plutôt fort" = "(6,11]",
    "Fort" = "(11,43.1]",
  )
indiv_dist$com_apl_psy_rec <- relevel(indiv_dist$com_apl_psy_rec, ref = "Faible")
```




## En continu

### Tous

```{r}
indiv_mod_df <- indiv_dist #%>% 
  # filter(tuu2017 %in% c("Unité urbaine de Paris", "Unité urbaine de 200 000 à 1 999 999 habitants","Unité urbaine de 100 000 à 199 999 habitants", "Unité urbaine de 50 000 à 99 999 habitants", "Unité urbaine de 20 000 à 49 999 habitants"))# Plus urbain
  # filter(tuu2017 %in% c("0", "Unité urbaine de 2 000 à 4 999 habitants","Unité urbaine de 5 000 à 9 999 habitants", "Unité urbaine de 10 000 à 19 999 habitants"))# Plus rural
# %>% 
  # filter(tuu2017=="Unité urbaine de Paris")#Paris
nrow(indiv_mod_df)#nombre d'enquêtés concernés
```

```{r}
reg0bis <- function(var) {model <- lm_robust(var ~ iris_pct_immi+ tuu2017+iris_pct_dip_bac, weights = poidsi_entier,data = indiv_mod_df)
return(model)}
```

```{r, echo = FALSE}
model_urg <- reg0bis(indiv_mod_df$dist_min_urg)
model_mat <- reg0bis(indiv_mod_df$dist_min_mat)
model_medge <- reg0bis(indiv_mod_df$lib_dist_min_medge)
model_medge_apl <- reg0bis(indiv_mod_df$com_apl_mg)
model_gyn <- reg0bis(indiv_mod_df$lib_dist_min_gynéco)
model_gyn_apl <- reg0bis(indiv_mod_df$com_apl_gyn)
model_sf <- reg0bis(indiv_mod_df$lib_dist_min_sf)
model_sf_apl <- reg0bis(indiv_mod_df$com_apl_sagf)

b <- list(geom_vline(xintercept = 0, color = 'black'))

mp <- modelplot(list("Urgences" = model_urg, "Maternité" = model_mat, "Généraliste" = model_medge, "Généraliste (APL)"=model_medge_apl, "Gynécologue" = model_gyn, "Gynécologue (APL)" = model_gyn_apl, "Sage-femme" = model_sf, "Sage-femme (APL)" = model_sf_apl),
                background = b, coef_omit = "Interc|tuu2017\\w*", coef_map = c("iris_pct_immi"="Pourcentage d'immigrés dans l'IRIS", "iris_pct_dip_bac" = "Pourcentage de diplômés du bac dans l'IRIS"))

alpha_values <- ifelse(mp$data$p.value > 0.05, 0.3, 1)

mp + theme_minimal() +
  scale_alpha_manual(
    values = alpha_values  )+labs(caption = "Champ : tout type d'IRIS")
```
### Paris

```{r}
indiv_mod_df_paris <- indiv_dist %>% 
  # filter(tuu2017 %in% c("Unité urbaine de Paris", "Unité urbaine de 200 000 à 1 999 999 habitants","Unité urbaine de 100 000 à 199 999 habitants", "Unité urbaine de 50 000 à 99 999 habitants", "Unité urbaine de 20 000 à 49 999 habitants"))# Plus urbain
  # filter(tuu2017 %in% c("0", "Unité urbaine de 2 000 à 4 999 habitants","Unité urbaine de 5 000 à 9 999 habitants", "Unité urbaine de 10 000 à 19 999 habitants"))# Plus rural
# %>% 
  filter(tuu2017=="Unité urbaine de Paris")#Paris
nrow(indiv_mod_df_paris)#nombre d'enquêtés concernés
```

```{r}
reg0bis <- function(var) {model <- lm_robust(var ~ iris_pct_immi+iris_pct_dip_bac, weights = poidsi_entier,data = indiv_mod_df_paris)
return(model)}
```

```{r, echo = FALSE}
model_urg <- reg0bis(indiv_mod_df_paris$dist_min_urg)
model_mat <- reg0bis(indiv_mod_df_paris$dist_min_mat)
model_medge <- reg0bis(indiv_mod_df_paris$lib_dist_min_medge)
model_medge_apl <- reg0bis(indiv_mod_df_paris$com_apl_mg)
model_gyn <- reg0bis(indiv_mod_df_paris$lib_dist_min_gynéco)
model_gyn_apl <- reg0bis(indiv_mod_df_paris$com_apl_gyn)
model_sf <- reg0bis(indiv_mod_df_paris$lib_dist_min_sf)
model_sf_apl <- reg0bis(indiv_mod_df_paris$com_apl_sagf)

b <- list(geom_vline(xintercept = 0, color = 'black'))

mp <- modelplot(list("Urgences" = model_urg, "Maternité" = model_mat, "Généraliste" = model_medge, "Généraliste (APL)"=model_medge_apl, "Gynécologue" = model_gyn, "Gynécologue (APL)" = model_gyn_apl, "Sage-femme" = model_sf, "Sage-femme (APL)" = model_sf_apl),
                background = b, coef_omit = "Interc", coef_map = c("iris_pct_immi"="Pourcentage d'immigrés dans l'IRIS", "iris_pct_dip_bac" = "Pourcentage de diplômés du bac dans l'IRIS"))

alpha_values <- ifelse(mp$data$p.value > 0.05, 0.3, 1)

mp + theme_minimal() +
  scale_alpha_manual(
    values = alpha_values  )+labs(caption = "Champ : Unité urbaine de Paris")
```


### Grandes villes 

```{r}
indiv_mod_df_ville <- indiv_dist %>% 
  filter(tuu2017 %in% c("Unité urbaine de Paris", "Unité urbaine de 200 000 à 1 999 999 habitants","Unité urbaine de 100 000 à 199 999 habitants", "Unité urbaine de 50 000 à 99 999 habitants", "Unité urbaine de 20 000 à 49 999 habitants"))# Plus urbain
  # filter(tuu2017 %in% c("0", "Unité urbaine de 2 000 à 4 999 habitants","Unité urbaine de 5 000 à 9 999 habitants", "Unité urbaine de 10 000 à 19 999 habitants"))# Plus rural
# %>% 
  # filter(tuu2017=="Unité urbaine de Paris")#Paris
nrow(indiv_mod_df_ville)#nombre d'enquêtés concernés
```


```{r}
reg0bis <- function(var) {model <- lm_robust(var ~ iris_pct_immi+iris_pct_dip_bac+tuu2017, weights = poidsi_entier,data = indiv_mod_df_ville)
return(model)}
```

```{r, echo = FALSE}
model_urg <- reg0bis(indiv_mod_df_ville$dist_min_urg)
model_mat <- reg0bis(indiv_mod_df_ville$dist_min_mat)
model_medge <- reg0bis(indiv_mod_df_ville$lib_dist_min_medge)
model_medge_apl <- reg0bis(indiv_mod_df_ville$com_apl_mg)
model_gyn <- reg0bis(indiv_mod_df_ville$lib_dist_min_gynéco)
model_gyn_apl <- reg0bis(indiv_mod_df_ville$com_apl_gyn)
model_sf <- reg0bis(indiv_mod_df_ville$lib_dist_min_sf)
model_sf_apl <- reg0bis(indiv_mod_df_ville$com_apl_sagf)

b <- list(geom_vline(xintercept = 0, color = 'black'))

mp <- modelplot(list("Urgences" = model_urg, "Maternité" = model_mat, "Généraliste" = model_medge, "Généraliste (APL)"=model_medge_apl, "Gynécologue" = model_gyn, "Gynécologue (APL)" = model_gyn_apl, "Sage-femme" = model_sf, "Sage-femme (APL)" = model_sf_apl),
                background = b, coef_omit = "Interc|tuu2017\\w*", coef_map = c("iris_pct_immi"="Pourcentage d'immigrés dans l'IRIS", "iris_pct_dip_bac" = "Pourcentage de diplômés du bac dans l'IRIS"))

alpha_values <- ifelse(mp$data$p.value > 0.05, 0.3, 1)

mp + theme_minimal() +
  scale_alpha_manual(
    values = alpha_values  )+labs(caption = "Champ : Unités urbaines de plus de 20 000 habitants")
```

### Interaction : ne fonctionne pas
```{r}
reg0bis <- function(var) {model <- lm_robust(var ~ iris_pct_immi*iris_pct_dip_bac+tuu2017, weights = poidsi_entier,data = indiv_mod_df_ville)
return(model)}
```

```{r, echo = FALSE}
model_urg <- reg0bis(indiv_mod_df_ville$dist_min_urg)
model_mat <- reg0bis(indiv_mod_df_ville$dist_min_mat)
model_medge <- reg0bis(indiv_mod_df_ville$lib_dist_min_medge)
model_medge_apl <- reg0bis(indiv_mod_df_ville$com_apl_mg)
model_gyn <- reg0bis(indiv_mod_df_ville$lib_dist_min_gynéco)
model_gyn_apl <- reg0bis(indiv_mod_df_ville$com_apl_gyn)
model_sf <- reg0bis(indiv_mod_df_ville$lib_dist_min_sf)
model_sf_apl <- reg0bis(indiv_mod_df_ville$com_apl_sagf)

b <- list(geom_vline(xintercept = 0, color = 'black'))

mp <- modelplot(list("Urgences" = model_urg, "Maternité" = model_mat, "Généraliste" = model_medge, "Généraliste (APL)"=model_medge_apl, "Gynécologue" = model_gyn, "Gynécologue (APL)" = model_gyn_apl, "Sage-femme" = model_sf, "Sage-femme (APL)" = model_sf_apl),
                background = b, coef_omit = "Interc|tuu2017\\w*")

alpha_values <- ifelse(mp$data$p.value > 0.05, 0.3, 1)

mp + theme_minimal() +
  scale_alpha_manual(
    values = alpha_values  )
```

## En discret
Relou parce que changer vers du logistique 
